name: Build Hugo

permissions:
  contents: read
  pull-requests: write
  statuses: write
on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs: # This exposes the CID output of the action to the rest of the workflow
      cid: ${{ steps.deploy.outputs.cid }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.1'
          extended: true

      - name: Build
        run: hugo --minify

      - run: mkdir -p publish

      - run: mv public publish/6kgrunw3nwza-hexcamp-dev-blog

      - uses: ipfs/ipfs-deploy-action@v1
        name: Deploy to Storacha and IPFS Cluster
        id: deploy
        with:
          path-to-deploy: publish
          storacha-key: ${{ secrets.STORACHA_KEY }}
          storacha-proof: ${{ secrets.STORACHA_PROOF }}
          cluster-url: ${{ secrets.CLUSTER_URL }}
          cluster-user: ${{ secrets.CLUSTER_USER }}
          cluster-password: ${{ secrets.CLUSTER_PASSWORD }}
          github-token: ${{ github.token }}

      - name: Check dns trace
        run: dig +trace 6kgv3nw3nw2q.seahex.org

      - name: Check dns trace after CNAME
        run: dig +trace 5.6.6.6.6.6.6.6.6.6.6.6.5.2.3.20.h3.seahex.org.

      - name: Check dns
        run: dig 6kgv3nw3nw2q.seahex.org

      - name: Test ping
        run: ping -c 1 6kgv3nw3nw2q.seahex.org || true

      - name: Call hackmd-updater API with CID
        run: curl -X POST -u admin:${{ secrets.HACKMD_UPDATER_PASSWORD }} https://6kgv3nw3nw2q.seahex.org/publish/${{ steps.deploy.outputs.cid }}

